### ISSUE TITLE
Seems like my AddIn class is never loaded

### ISSUE THREAD

**Issue by xgouchet** [wolfgangimig/joa#6]
I followed your tutorial, created my own AddIn class with the same Annotations, and a Ribbon xml file, located in the resources under the same package name. 

When I start Outlook (2013), the ribbon entry is created correctly, and all the items appear, but the button clicked callbacks never get called. I added logs and breakpoint, and it seems like my class is never loaded (I added an empty constructor, and it never gets called either). 

Is there something I might be missing.

**Comment by wolfgangimig** [comment]
The ribbon controls are displayed after GetCustomUI has been called. This function returns the Ribbon.xml file content. If you overload this function in your Addin, you should be able to hit a breakpoint there. 


	@Override
	public String GetCustomUI(String ribbonId) {
		return super.GetCustomUI(ribbonId);
	}


Make sure that your callback handlers are declared as **public** and they have exactly the same name in the Ribbon.xml and the Addin class.

**Comment by xgouchet** [comment]
Thanks a lot for your help Wolfgang :)
